# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(983, 545)
        Form.setStyleSheet("color: qradialgradient(spread:repeat, cx:0.5, cy:0.5, radius:0.077, fx:0.5, fy:0.5, stop:0 rgba(0, 169, 255, 147), stop:0.497326 rgba(0, 0, 0, 147), stop:1 rgba(0, 169, 255, 147));")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setStyleSheet("#Form{\n"
"    background:url(:/D/invest.jpg);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(340, 150, 251, 261))
        self.frame_2.setStyleSheet("QFrame {\n"
"    background-color: #333; /* 设置背景颜色 */ \n"
"     border-radius: 10px;\n"
"    \n"
"}\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(60, 70, 161, 41))
        self.frame_3.setStyleSheet("QLineEdit {\n"
"     background-color: transparent;\n"
"    border: none; /* 移除边框 */\n"
"    color: #717072; /* 设置文字颜色为灰色 */\n"
"     border-bottom:1px solid #717072;\n"
"\n"
"}    ")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.username = QtWidgets.QLineEdit(self.frame_3)
        self.username.setGeometry(QtCore.QRect(0, 10, 113, 20))
        self.username.setObjectName("username")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setGeometry(QtCore.QRect(60, 120, 161, 41))
        self.frame_4.setStyleSheet("QLineEdit {\n"
"    border: none; /* 移除边框 */\n"
"    color: gray; /* 设置文字颜色为灰色 */\n"
"     background-color: transparent;\n"
"    text-decoration: underline;\n"
"border-bottom:1px solid #717072;\n"
"\n"
"}    ")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.password = QtWidgets.QLineEdit(self.frame_4)
        self.password.setGeometry(QtCore.QRect(0, 10, 113, 20))
        self.password.setDragEnabled(False)
        self.password.setReadOnly(False)
        self.password.setClearButtonEnabled(False)
        self.password.setObjectName("password")
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setGeometry(QtCore.QRect(30, 210, 191, 41))
        self.frame_5.setStyleSheet("QPushButton {\n"
"    background-color: transparent; /* 移除背景色 */\n"
"    border: none; /* 移除边框 */\n"
"    color: gray; /* 设置文字颜色，可以根据需要更改 */\n"
"    font: bold 8px; /* 设置文字样式和大小，可以根据需要更改 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: gray; /* 按下时文字颜色变化，可以根据需要更改 */\n"
"}\n"
"")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.quick_register = QtWidgets.QPushButton(self.frame_5)
        self.quick_register.setGeometry(QtCore.QRect(130, 10, 61, 20))
        self.quick_register.setIconSize(QtCore.QSize(12, 12))
        self.quick_register.setCheckable(False)
        self.quick_register.setAutoDefault(True)
        self.quick_register.setObjectName("quick_register")
        self.forget_password = QtWidgets.QPushButton(self.frame_5)
        self.forget_password.setGeometry(QtCore.QRect(0, 10, 56, 17))
        self.forget_password.setObjectName("forget_password")
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        self.frame_6.setGeometry(QtCore.QRect(10, 170, 231, 41))
        self.frame_6.setStyleSheet("QPushButton {\n"
"    background-color: red; /* 设置背景颜色为红色 */\n"
"    color: white; /* 设置文字颜色为白色 */\n"
"    border: none; /* 可选：移除边框 */\n"
"    font: bold 8px; /* 设置文字样式和大小 */\n"
"    font-weight: 300;\n"
"    padding: 6px; /* 设置内边距，使按钮更大一些 */\n"
"    border-radius: 5px;    \n"
"}\n"
"")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.login_botton = QtWidgets.QPushButton(self.frame_6)
        self.login_botton.setGeometry(QtCore.QRect(20, 10, 191, 21))
        self.login_botton.setObjectName("login_botton")
        self.listView = QtWidgets.QListView(self.frame)
        self.listView.setGeometry(QtCore.QRect(-420, -70, 1431, 611))
        self.listView.setStyleSheet("background-image: url(:/invest_2.webp);\n"
"background-size:60,60;")
        self.listView.setObjectName("listView")
        self.listView.raise_()
        self.frame_2.raise_()
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.username.setText(_translate("Form", "請輸入您的使用者名稱"))
        self.username.setPlaceholderText(_translate("Form", "請輸入您的賬號"))
        self.password.setPlaceholderText(_translate("Form", "請輸入您的密碼"))
        self.quick_register.setText(_translate("Form", "立即註冊"))
        self.forget_password.setText(_translate("Form", "忘記密碼"))
        self.login_botton.setText(_translate("Form", "登 錄"))
import backgroud_rc
